# When using this file, its name should read 'docker-compose.yml'
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret

        # I used Heroku's postgres free database tier  
        databases:
          default:
            connector: postgres
            host: HOST
            database: DATABASE
            user: USER
            password: PASSWORD
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true